### ISSUE TITLE
Sql pipeline mysql issue

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/pipelines#22]
I tried to run the sql pipeline with a local mysql db, and it seems there's an issue around session/connection object usage.

trace:

> (python-dlt-verified-pipelines-py3.9) bash-3.2$ python3 sql_database_pipeline.py 
Traceback (most recent call last):
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 316, in extract
    self._extract_source(storage, source, max_parallel_items, workers)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 743, in _extract_source
    extract_id = self._iterate_source(storage, source, pipeline_schema, max_parallel_items, workers)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 758, in _iterate_source
    extractor = extract(extract_id, source, storage, max_parallel_items=max_parallel_items, workers=workers)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/extract/extract.py", line 81, in extract
    for pipe_item in PipeIterator.from_pipes(source.resources.selected_pipes, max_parallel_items=max_parallel_items, workers=workers, futures_poll_interval=futures_poll_interval):
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/extract/pipe.py", line 422, in __next__
    pipe_item = self._get_source_item()
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/extract/pipe.py", line 570, in _get_source_item
    item = next(gen)
  File "/Users/adrian/PycharmProjects/ll/python-dlt-verified-pipelines/pipelines/sql_database/source.py", line 19, in table_rows
    with conn.execute(table.select()) as result:
AttributeError: __enter__

The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/Users/adrian/PycharmProjects/ll/python-dlt-verified-pipelines/pipelines/sql_database_pipeline.py", line 24, in <module>
    info = pipeline.run(data)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 100, in _wrap
    step_info = f(self, *args, **kwargs)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 131, in _wrap
    return f(self, *args, **kwargs)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 491, in run
    self.extract(data, table_name=table_name, write_disposition=write_disposition, columns=columns, schema=schema)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 100, in _wrap
    step_info = f(self, *args, **kwargs)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 74, in _wrap
    rv = f(self, *args, **kwargs)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 60, in _wrap
    return f(self, *args, **kwargs)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 131, in _wrap
    return f(self, *args, **kwargs)
  File "/Users/adrian/Library/Caches/pypoetry/virtualenvs/python-dlt-verified-pipelines-7y5Gudle-py3.9/lib/python3.9/site-packages/dlt/pipeline/pipeline.py", line 325, in extract
    raise PipelineStepFailed(self, "extract", exc, runner.LAST_RUN_METRICS, ExtractInfo()) from exc
dlt.pipeline.exceptions.PipelineStepFailed: Pipeline execution failed at stage extract with exception:

`<class 'AttributeError'>
__enter__
(python-dlt-verified-pipelines-py3.9) bash-3.2$ B`

**Comment by adrianbr** [comment]
@steinitzu can you please have a look? 

my url looks like `database_url = "mysql+pymysql://root:pass@127.0.0.1/db"`

**Comment by steinitzu** [comment]
Hey @adrianbr , ah probably because I used sqlalchemy 2.0 (added in pyproject), could you try installing it.  
I realize now dlt itself depends on 1.4, but only using minimal parts for URL building so no breaking changes

**Comment by rudolfix** [comment]
@adrianbr you can mark this as bug ans assign @steinitzu to it

@steinitzu what is the adoption of SqlAlchemy 2.0? are we cutting many people out by requiring it?

**Comment by steinitzu** [comment]
@rudolfix I'm not sure what kind of packages people would use with dlt and sqlalchemy together, but I know a lot of projects are still on 1.4 so this could maybee cause dependency conflicts.  
All the major API changes in 2.0 are already present in 1.4 with deprecation warnings for a year, so generally 2.0 is a drop in replacment for code that's maintained, and it's not a lot of work to migrate in my experience.  

But still 2.0 release is pretty recent so for now probably best I adopt the pipeline. It's easy to support both versions.
